nginx:
  build: ./nginx/
  links:
  - app
  ports:
  - "80:80"

mongo:
  image: mongo

app:
  build: ./app/
  ports:
  - "3000:3000"
#   volumes:
#   - .:/code
  links:
  - mongo
  environment:
  - MONGO_URI=mongo
  - NODE_ENV=production

